name: eriktenhave
favicon: null
layout_spectrum: 0.5285664957482368
typography_spectrum: 0.2583333731163293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8587442287243903
  lightness: 0.0474424425046891
  saturation: 0.5717970514670014
  rhythmicContrast: 0.4336848498787731
purpose: []
